include:
  - path:
      - ./compose._network.yaml
      - ./compose._volumes.shared.yaml
      - ./compose._toolbox.yaml
      - ./compose._volumes.observability.yaml
      - ./compose._observability.yaml
      - ./compose._secrets.grafana.yaml
      - ./compose._secrets.telegram.yaml
      - ./compose._apps.yaml
      - ./compose._apps.staging.yaml
      - ./compose._app_prereqs.yaml
    project_directory: .
