auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/index_cache
    cache_ttl: 24h

  filesystem:
    directory: /var/loki/chunks

ingester:
  wal:
    enabled: true
    dir: /var/loki/wal

  chunk_idle_period: 30m
  max_chunk_age: 2h
  chunk_target_size: 1572864
  chunk_encoding: lz4

limits_config:
  allow_structured_metadata: true
  reject_old_samples: true
  reject_old_samples_max_age: 168h

  max_label_names_per_series: 30
  max_line_size: 256KB

  retention_period: 168h

compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /var/loki/rules
  rule_path: /var/loki/rules-tmp
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  ring:
    kvstore:
      store: inmemory
  enable_api: true
