[pytest]
django_find_project = false
DJANGO_SETTINGS_MODULE = django_app.settings
pythonpath = app
python_files = test_*.py *_test.py
testpaths = tests
addopts =
  -q
  --disable-warnings
  --maxfail=1
  --strict-config
  --strict-markers
  --cov=app
  --cov-report=term-missing
  --cov-report=xml
